### ISSUE TITLE
Add support to create files in SHared Memory

### ISSUE THREAD

**Issue by mcanevet** [cyberark/summon#107]
It would be great to be able to create temporary files in shared memory.
For example, Kubernetes context is usually stored in `~/.kube/config`, there is a `KUBECONFIG` environment variable to tell `kubectl` or other tools where the config file is, but no environment variable to store the credentials to access a cluster.
What I'd like is to be able to do that in `secrets.yml`:
```yaml
---
kube_config: !file secret/containing/my/context
KUBECONFIG: /dev/shm/kube_config
```
So that I'm able to transparently run `summon kubectl` without having to log into my cluster first.
