### ISSUE TITLE
Common environment not loaded if environment not specified

### ISSUE THREAD

**Issue by izgeri** [cyberark/summon#130]
I have a secrets.yml with a common environment and two custom envs:
```
common:
  ENV_VAR: !var my/value

dev:
  OTHER_ENV_VAR: !var my/dev/value

prod:
  OTHER_ENV_VAR: !var my/prod/value
```

I expected that when I ran `summon my-script` and did not specify an environment, that the `common` section would still be invoked - but it was not.

However when I run `summon -e dev my-script` or `summon -e prod my-script`, Summon invokes the `common` env and the env specified with the `-e` flag, and it does as expected.
